// Package lazy renders a vimpin manifest as a lazy.nvim plugin spec table.
package lazy

import (
	"fmt"
	"io"
	"strings"

	"github.com/gr1m0h/vimpin/internal/adapter"
	"github.com/gr1m0h/vimpin/internal/manifest"
)

const adapterName = "lazy"

type Adapter struct{}

func init() {
	adapter.Register(Adapter{})
}

func (Adapter) Name() string { return adapterName }

// Generate writes a Lua module that returns a list of lazy.nvim plugin specs.
// Entries with layer="override" emit a minimal { "repo", commit = ... } spec
// that lazy.nvim merges into the matching distribution spec; entries with
// layer="user" (or unset) carry the branch field as well so detached-HEAD
// fetches still have the right ref to look at.
func (Adapter) Generate(m *manifest.Manifest, plugins []manifest.Plugin, w io.Writer) error {
	var b strings.Builder
	b.WriteString("-- Generated by vimpin. DO NOT EDIT.\n")
	b.WriteString("-- Source of truth: vimpin.toml\n")
	b.WriteString("return {\n")
	for _, p := range plugins {
		writeSpec(&b, p)
	}
	b.WriteString("}\n")
	_, err := io.WriteString(w, b.String())
	return err
}

func writeSpec(b *strings.Builder, p manifest.Plugin) {
	override := p.Layer == "override"

	if p.Reason != "" {
		fmt.Fprintf(b, "  -- %s: %s\n", p.Repo, escapeComment(p.Reason))
	}
	fmt.Fprintf(b, "  { %q", p.Repo)
	if p.Commit != "" {
		fmt.Fprintf(b, ", commit = %q", p.Commit)
	}
	// branch is informational for lazy.nvim when commit is detached. Skip
	// it on overrides so we touch only the commit on the distribution spec.
	if !override && p.Branch != "" {
		fmt.Fprintf(b, ", branch = %q", p.Branch)
	}
	b.WriteString(" },\n")
}

// escapeComment trims a reason string so it cannot break out of a Lua line
// comment by introducing a newline.
func escapeComment(s string) string {
	return strings.ReplaceAll(strings.ReplaceAll(s, "\n", " "), "\r", " ")
}
