package lazy

import (
	"bytes"
	"strings"
	"testing"

	"github.com/gr1m0h/vimpin/internal/manifest"
)

func TestGenerateUserLayer(t *testing.T) {
	m := &manifest.Manifest{Schema: manifest.SchemaV1}
	plugins := []manifest.Plugin{
		{
			Repo:   "ggandor/leap.nvim",
			Commit: strings.Repeat("a", 40),
			Tag:    "v0.1.5",
			Branch: "main",
			Layer:  "user",
			Group:  "core",
		},
	}
	var buf bytes.Buffer
	if err := (Adapter{}).Generate(m, plugins, &buf); err != nil {
		t.Fatalf("Generate: %v", err)
	}
	s := buf.String()
	if !strings.Contains(s, `"ggandor/leap.nvim"`) {
		t.Errorf("missing repo in output:\n%s", s)
	}
	if !strings.Contains(s, `commit = "`+strings.Repeat("a", 40)+`"`) {
		t.Errorf("missing commit in output:\n%s", s)
	}
	if !strings.Contains(s, `branch = "main"`) {
		t.Errorf("user-layer entry should carry branch:\n%s", s)
	}
}

func TestGenerateOverrideLayerOmitsBranch(t *testing.T) {
	m := &manifest.Manifest{Schema: manifest.SchemaV1}
	plugins := []manifest.Plugin{
		{
			Repo:   "nvim-treesitter/nvim-treesitter",
			Commit: strings.Repeat("b", 40),
			Branch: "master",
			Layer:  "override",
			Reason: "pin to a specific commit",
		},
	}
	var buf bytes.Buffer
	if err := (Adapter{}).Generate(m, plugins, &buf); err != nil {
		t.Fatalf("Generate: %v", err)
	}
	s := buf.String()
	if strings.Contains(s, "branch =") {
		t.Errorf("override-layer entry should not include branch:\n%s", s)
	}
	if !strings.Contains(s, `commit = "`+strings.Repeat("b", 40)+`"`) {
		t.Errorf("missing commit:\n%s", s)
	}
	if !strings.Contains(s, "-- nvim-treesitter/nvim-treesitter: pin to a specific commit") {
		t.Errorf("missing reason comment:\n%s", s)
	}
}

func TestGenerateHeader(t *testing.T) {
	m := &manifest.Manifest{Schema: manifest.SchemaV1}
	var buf bytes.Buffer
	if err := (Adapter{}).Generate(m, nil, &buf); err != nil {
		t.Fatalf("Generate: %v", err)
	}
	s := buf.String()
	if !strings.HasPrefix(s, "-- Generated by vimpin") {
		t.Errorf("missing header:\n%s", s)
	}
	if !strings.Contains(s, "return {") || !strings.HasSuffix(strings.TrimSpace(s), "}") {
		t.Errorf("expected lua return table:\n%s", s)
	}
}
